# Generated by Django 5.1.6 on 2025-02-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_city_product_country_product_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bulk price per unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_threshold',
            field=models.IntegerField(blank=True, help_text='Minimum quantity for bulk pricing', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bulk_eligible',
            field=models.BooleanField(default=False, help_text='Available for bulk orders?'),
        ),
    ]
